#!/bin/bash
# Initialize or destroy the environment for running Namakanui

case $1 in
    start) 
        echo "Prepare the env for running Namakanui..."
        systemctl --user start nk_pcand nk_temp_mon nk_drama nk_task
        echo "systemd (user) services started."
        python3 /jac_sw/itsroot/install/namakanui/bin/Linux-x86_64/namakanui_gui.py NAMAKANUI &
        echo "Namakanui GUI launched."
        ;;
    stop) 
        echo "Closing the Namakanui env..."
        systemctl --user stop nk_task nk_drama nk_pcand nk_temp_mon
        echo "Namakanui terminated."
        ;;
    *) 
        printf "Usage: $0 [start | stop]
        - start: Initialize the environment for running Namakanui. 
                 Make sure to close the ALMA front end UI first.
        - stop:  End and restore the environment for running the ALMA UI.\n" 
        ;;
esac