#!/bin/bash
# Initialize or destroy the environment for running Namakanui

case $1 in
    start) 
        echo "Prepare the env for running Namakanui..."
        systemctl --user start nk_pcand nk_temp_mon nk_drama nk_task
        echo "systemd (user) services started."
        python3 /jac_sw/itsroot/install/namakanui/bin/Linux-x86_64/namakanui_gui.py NAMAKANUI &
        echo "Namakanui GUI launched."
        ;;
    stop) 
        echo "Closing the Namakanui env..."
        systemctl --user stop nk_task nk_drama
        systemctl --user start nk_temp_mon nk_pcand
        #python3 /jac_sw/itsroot/install/namakanui/bin/Linux-x86_64/namakanui_power_down.py
        # Power down all the cartridge power. Can't restart operations using Namakanui alone!!
        systemctl --user stop nk_temp_mon nk_pcand
        echo "Namakanui terminated."
        ;;
    eng)
        echo "Entering the engineering mode..."
        systemctl --user stop nk_task nk_drama 
        systemctl --user start nk_temp_mon nk_pcand
        echo "Engineering mode started."
        ;;
    *) 
        printf "Usage: $0 [ start | stop | eng ]
        - start: Initialize the environment for running Namakanui. 
                 Make sure to close the ALMA FE UI first.
        - stop:  Stop and clean the Namakanui environment.
        - eng:   Enter the engineering mode. \n" 
        ;;
esac